# Exercise 1

In [10]:
import torch

In [18]:
def activation(x):
    """ Sigmoid activation function
    
        Arguments
        -----------
        x: torch.tensor
    """
    return 1/(1+torch.exp(-x))

In [19]:
###Generate some data
torch.manual_seed(7)

#Features are 5 random normal variables
features = torch.randn((1,5)) 
#contains values randomly distributed according to the normal distribution with a mean of zero and standard deviation of one

#True weights for our data, random normal variables again
weights = torch.randn_like(features)

#and a true bias term
bias = torch.randn((1,1))

In [20]:
print(features)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])


In [21]:
print(weights)

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])


In [22]:
print(bias)

tensor([[0.3177]])


> **Exercise**: Calculate the output of the network with input features `features`, weights `weights`, and bias `bias`. Similar to Numpy, PyTorch has a [`torch.sum()`](https://pytorch.org/docs/stable/torch.html#torch.sum) function, as well as a `.sum()` method on tensors, for taking sums. Use the function `activation` defined above as the activation function.

In [23]:
y = activation(torch.sum(features * weights) + bias)

#another way
y = activation((features * weights).sum() + bias)

In [17]:
#If we do it using torch.mm()


torch.mm(features, weights)

RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorMath.cpp:752

The error is because tensors are not in correct shape. For matrix multiplication, the number of columns in first matrix should be equal to rows in second matrix but here the matrices sizes are (1,5) and (1,5)

We havr the options of using .reshape(), resize_(), or .view() methods

In [24]:
y = activation(torch.mm(features,weights.view(5,1)) + bias)

$$
y =  f_2 \! \left(\, f_1 \! \left(\vec{x} \, \mathbf{W_1}\right) \mathbf{W_2} \right)
$$

The network can be understand as input --> hidden --> output. vec{x} multiplied with W1 (weights for input layer) will give output for hidden layer which inturn are input for output layer. So we have to multiply by weights of hidden layer. 

In [28]:
#Generate some data

torch.manual_seed(7)

#Features are 3 random variables
features = torch.randn((1, 3))

#Define the size of each layer in network

n_input = features.shape[1]
n_hidden = 2
n_output = 1


#Weights for input to hidden layer
W1 = torch.randn((n_input, n_hidden))

#Weights from hidden layer to output layer
W2 = torch.randn((n_hidden, n_output))

#Add bias term for each layer

B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))



> **Exercise:** Calculate the output for this multi-layer network using the weights `W1` & `W2`, and the biases, `B1` & `B2`. 

In [27]:
print(features)

tensor([[-0.1468,  0.7861,  0.9468]])


In [33]:
print(W1)

tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])


In [34]:
print(W2)

tensor([[-1.6822],
        [ 0.3177]])


In [35]:
print(B1,B2)

tensor([[0.1328, 0.1373]]) tensor([[0.2405]])


In [31]:
h = activation(torch.mm(features, W1) + B1)
y = activation(torch.mm(h, W2) + B2)

In [32]:
print(y)

tensor([[0.3171]])


## Numpy to torch and Back!

In [37]:
import numpy as np

a = np.random.rand(4,3)
a

array([[0.84444781, 0.68912092, 0.500826  ],
       [0.2852421 , 0.77274856, 0.60804496],
       [0.01998783, 0.30228675, 0.73437857],
       [0.11626338, 0.4830554 , 0.76032999]])

In [38]:
b = torch.from_numpy(a)
b

tensor([[0.8444, 0.6891, 0.5008],
        [0.2852, 0.7727, 0.6080],
        [0.0200, 0.3023, 0.7344],
        [0.1163, 0.4831, 0.7603]], dtype=torch.float64)

In [39]:
b.numpy()

array([[0.84444781, 0.68912092, 0.500826  ],
       [0.2852421 , 0.77274856, 0.60804496],
       [0.01998783, 0.30228675, 0.73437857],
       [0.11626338, 0.4830554 , 0.76032999]])

The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.

In [40]:
b.mul_(2)

tensor([[1.6889, 1.3782, 1.0017],
        [0.5705, 1.5455, 1.2161],
        [0.0400, 0.6046, 1.4688],
        [0.2325, 0.9661, 1.5207]], dtype=torch.float64)

In [43]:
a

array([[1.68889561, 1.37824184, 1.001652  ],
       [0.57048421, 1.54549711, 1.21608992],
       [0.03997566, 0.60457351, 1.46875715],
       [0.23252676, 0.9661108 , 1.52065999]])

# Exercise 2